ALTER TABLE users ADD COLUMN IF NOT EXISTS extra_life_boosts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS extra_time_boosts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS double_xp_boosts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE quiz_sessions ADD COLUMN IF NOT EXISTS extra_time_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE quiz_sessions ADD COLUMN IF NOT EXISTS extra_life_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE quiz_sessions ADD COLUMN IF NOT EXISTS xp_multiplier_used BOOLEAN NOT NULL DEFAULT FALSE;