ALTER TABLE users ADD COLUMN IF NOT EXISTS extra_life_boosts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS extra_time_boosts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS double_xp_boosts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS biblical_characters ALTER COLUMN image_url TYPE TEXT;
ALTER TABLE IF EXISTS biblical_characters ALTER COLUMN short_summary TYPE TEXT;
ALTER TABLE IF EXISTS biblical_characters ALTER COLUMN historical_period TYPE TEXT;
ALTER TABLE IF EXISTS biblical_characters ALTER COLUMN narrative_role TYPE TEXT;

ALTER TABLE quiz_sessions ADD COLUMN IF NOT EXISTS extra_time_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE quiz_sessions ADD COLUMN IF NOT EXISTS extra_life_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE quiz_sessions ADD COLUMN IF NOT EXISTS xp_multiplier_used BOOLEAN NOT NULL DEFAULT FALSE;